apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-gpu-plugin
  namespace: argocd
spec:
  project: default
  source:
    # Điền đường dẫn tới kho lưu trữ GitHub chứa file YAML của ngài
    repoURL: 'https://github.com/hieu180230/portfolioo141-k8s.git' 
    targetRevision: main
    # Trỏ đúng vào thư mục chứa cái file `mock-gpu-plugin.yaml` ban nãy
    path: mock-gpu
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true