frontend:
  image: "hieu18022004/portfolioo141"
  tag: "2026-04-22-a6dae22"
  replicas: 2
env:
  internalApiUrl: "http://p-service-be.portfolio-backend.svc.cluster.local:8000"
  r2CloudflareUrl: "https://pub-b4c7a5ad511a4c668ed49987987a8fe5.r2.dev"
ingress:
  domain: "nnhieu.duckdns.org"
  tlsSecretName: "portfolio-tls-secret"
  # rateLimitMiddleware: "portfolioo141-brutal-rate-limit@kubernetescrd"
