apiVersion: apps/v1
kind: Deployment
metadata: 
  name: p-deployment
  labels:
    app: portfolioo141
spec:
  replicas: {{ .Values.frontend.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: portfolioo141
  template:
    metadata:
      labels: 
        app: portfolioo141
    spec:
      containers:
        - name: portfolioo141
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: "{{ .Values.env.internalApiUrl }}"
            - name: NEXT_PUBLIC_R2_PUBLIC_URL
              value: "{{ .Values.env.r2CloudflareUrl }}"
          #resources restriction
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          #health check
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10